nelmio_cors:
    defaults:
        origin_regex: true
        allow_credentials: false
        allow_origin: ['*']
        allow_headers: ['Content-Type', 'Authorization', 'Accept', 'Origin', 'X-Requested-With', 'X-Total-Count']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
#        expose_headers: ['Link', 'X-Total-Count']  # Add 'X-Total-Count' here
        max_age: 3600
    paths:
        '^/api/': ~
