nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_headers: ['Content-Type', 'Authorization', 'Accept', 'Origin', 'X-Requested-With', 'X-Total-Count']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE', 'PATCH']
        expose_headers: ['Link']  # Add 'X-Total-Count' here
        max_age: 3600
    paths:
        '^/': null
        '^/api/':
            allow_origin: [ '*' ]
