vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        media_object:
            uri_prefix: /media
            upload_destination: '%kernel.project_dir%/public/media'
            # Will rename uploaded files using a uniqueid as a suffix.
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        brands_media_object:
            uri_prefix: /media/brands
            upload_destination: '%kernel.project_dir%/public/media/brands'
            # Will rename uploaded files using a uniqueid as a suffix.
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        variants_media_object:
            uri_prefix: /media/variants
            upload_destination: '%kernel.project_dir%/public/media/variants'
            # Will rename uploaded files using a uniqueid as a suffix.
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        categories_media_object:
            uri_prefix: /media/categories
            upload_destination: '%kernel.project_dir%/public/media/categories'
            # Will rename uploaded files using a uniqueid as a suffix.
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        subcategories_media_object:
            uri_prefix: /media/subcategories
            upload_destination: '%kernel.project_dir%/public/media/subcategories'
            # Will rename uploaded files using a uniqueid as a suffix.
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer